package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GOODS.
 */
public class Goods {

    private Long goods_id;
    private Integer goods_rank;
    private Integer goods_home_type;
    private String goods_name;
    private String goods_detail;
    private String goods_user_avatar;
    private String goods_image_url;
    private Integer goods_favorites_num;
    private Integer goods_comment_num;
    private String goods_user_cert_info;
    private String goods_user_nickname;
    private Integer goods_price;
    private Integer goods_user_id;
    private String goods_release_time;
    private Integer goods_class_id;
    private Integer goods_trade_place_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Goods() {
    }

    public Goods(Long goods_id) {
        this.goods_id = goods_id;
    }

    public Goods(Long goods_id, Integer goods_rank, Integer goods_home_type, String goods_name, String goods_detail, String goods_user_avatar, String goods_image_url, Integer goods_favorites_num, Integer goods_comment_num, String goods_user_cert_info, String goods_user_nickname, Integer goods_price, Integer goods_user_id, String goods_release_time, Integer goods_class_id, Integer goods_trade_place_id) {
        this.goods_id = goods_id;
        this.goods_rank = goods_rank;
        this.goods_home_type = goods_home_type;
        this.goods_name = goods_name;
        this.goods_detail = goods_detail;
        this.goods_user_avatar = goods_user_avatar;
        this.goods_image_url = goods_image_url;
        this.goods_favorites_num = goods_favorites_num;
        this.goods_comment_num = goods_comment_num;
        this.goods_user_cert_info = goods_user_cert_info;
        this.goods_user_nickname = goods_user_nickname;
        this.goods_price = goods_price;
        this.goods_user_id = goods_user_id;
        this.goods_release_time = goods_release_time;
        this.goods_class_id = goods_class_id;
        this.goods_trade_place_id = goods_trade_place_id;
    }

    public Long getGoods_id() {
        return goods_id;
    }

    public void setGoods_id(Long goods_id) {
        this.goods_id = goods_id;
    }

    public Integer getGoods_rank() {
        return goods_rank;
    }

    public void setGoods_rank(Integer goods_rank) {
        this.goods_rank = goods_rank;
    }

    public Integer getGoods_home_type() {
        return goods_home_type;
    }

    public void setGoods_home_type(Integer goods_home_type) {
        this.goods_home_type = goods_home_type;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getGoods_detail() {
        return goods_detail;
    }

    public void setGoods_detail(String goods_detail) {
        this.goods_detail = goods_detail;
    }

    public String getGoods_user_avatar() {
        return goods_user_avatar;
    }

    public void setGoods_user_avatar(String goods_user_avatar) {
        this.goods_user_avatar = goods_user_avatar;
    }

    public String getGoods_image_url() {
        return goods_image_url;
    }

    public void setGoods_image_url(String goods_image_url) {
        this.goods_image_url = goods_image_url;
    }

    public Integer getGoods_favorites_num() {
        return goods_favorites_num;
    }

    public void setGoods_favorites_num(Integer goods_favorites_num) {
        this.goods_favorites_num = goods_favorites_num;
    }

    public Integer getGoods_comment_num() {
        return goods_comment_num;
    }

    public void setGoods_comment_num(Integer goods_comment_num) {
        this.goods_comment_num = goods_comment_num;
    }

    public String getGoods_user_cert_info() {
        return goods_user_cert_info;
    }

    public void setGoods_user_cert_info(String goods_user_cert_info) {
        this.goods_user_cert_info = goods_user_cert_info;
    }

    public String getGoods_user_nickname() {
        return goods_user_nickname;
    }

    public void setGoods_user_nickname(String goods_user_nickname) {
        this.goods_user_nickname = goods_user_nickname;
    }

    public Integer getGoods_price() {
        return goods_price;
    }

    public void setGoods_price(Integer goods_price) {
        this.goods_price = goods_price;
    }

    public Integer getGoods_user_id() {
        return goods_user_id;
    }

    public void setGoods_user_id(Integer goods_user_id) {
        this.goods_user_id = goods_user_id;
    }

    public String getGoods_release_time() {
        return goods_release_time;
    }

    public void setGoods_release_time(String goods_release_time) {
        this.goods_release_time = goods_release_time;
    }

    public Integer getGoods_class_id() {
        return goods_class_id;
    }

    public void setGoods_class_id(Integer goods_class_id) {
        this.goods_class_id = goods_class_id;
    }

    public Integer getGoods_trade_place_id() {
        return goods_trade_place_id;
    }

    public void setGoods_trade_place_id(Integer goods_trade_place_id) {
        this.goods_trade_place_id = goods_trade_place_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
